# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ed88387204f67fafd6807c5aa9fb20153de2a79e5c4389c1402201d89e01cb98444c45dcb034aadf8f9470c11ecff3814957620c410d009ff83e392403235d06

test:
  secret_key_base: e7cb22c0c39cc842c3ebd9d165185d48a597a3b52a1970c08a961227626fa8790a19964804af4fe61b3bca30d382f2240e2a69d982d676b34aee28c03141b45b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
